services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fit
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"

  flower:
    image: mher/flower:2.0.1
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  mysql_data:
